# CUDA_VISIBLE_DEVICES=6 python run_partgvp.py \
#     --config-path=conf \
#     --config-name=config_partgvp \
#     train.epochs=120 \
#     data.test_mode=false \
#     train.use_wandb=true \
#     train.wandb_project=PartGVP-sequence \
#     data.dataset_name=scope \
#     model.seq_in=true \
#     data.split=random &

CUDA_VISIBLE_DEVICES=0 python run_partgvp.py \
    --config-path=conf \
    --config-name=config_partgvp \
    train.epochs=1 \
    data.test_mode=true \
    train.use_wandb=true \
    train.wandb_project=PartGVP-sequence \
    data.dataset_name=scope \
    model.seq_in=true \
    data.split=structure &

# CUDA_VISIBLE_DEVICES=2 python run_partgvp.py \
#     --config-path=conf \
#     --config-name=config_partgvp \
#     train.epochs=120 \
#     data.test_mode=false \
#     train.use_wandb=true \
#     train.wandb_project=PartGVP-sequence \
#     data.dataset_name=scope \
#     model.seq_in=true \
#     data.split=sequence &

# CUDA_VISIBLE_DEVICES=3 python run_partgvp.py \
#     --config-path=conf \
#     --config-name=config_partgvp \
#     train.epochs=120 \
#     data.test_mode=false \
#     train.use_wandb=true \
#     train.wandb_project=PartGVP-sequence \
#     data.dataset_name=enzymecommission \
#     model.seq_in=true \
#     data.split=random &

# CUDA_VISIBLE_DEVICES=4 python run_partgvp.py \
#     --config-path=conf \
#     --config-name=config_partgvp \
#     train.epochs=120 \
#     data.test_mode=false \
#     train.use_wandb=true \
#     train.wandb_project=PartGVP-sequence \
#     data.dataset_name=enzymecommission \
#     model.seq_in=true \
#     data.split=sequence &

# CUDA_VISIBLE_DEVICES=5 python run_partgvp.py \
#     --config-path=conf \
#     --config-name=config_partgvp \
#     train.epochs=120 \
#     data.test_mode=false \
#     train.use_wandb=true \
#     train.wandb_project=PartGVP-sequence \
#     data.dataset_name=enzymecommission \
#     model.seq_in=true \
#     data.split=structure &
