hydra:
  run:
    dir: ./outputs/${train.wandb_project}/${data.dataset_name}/${data.split}/${now:%Y-%m-%d-%H-%M-%S}
  output_subdir: null

data: 
  dataset_name: enzymecommission
  split: structure
  split_similarity_threshold: 0.7
  data_dir: /home/wangx86/partoken/partoken-protein/data
  test_mode: false  # Set to true for testing with limited data sizes (100 train, 20 val, 20 test)

model:
  node_in_dim: [6, 3]
  node_h_dim: [100, 16]
  edge_in_dim: [32, 1]
  edge_h_dim: [32, 1]
  num_layers: 3
  drop_rate: 0.1
  pooling: sum
  seq_in: false
  # Partitioner hyperparameters
  max_clusters: 5
  nhid: 50
  k_hop: 1
  cluster_size_max: 15
  termination_threshold: 0.95
  tau_init: 1.0
  tau_min: 0.1
  tau_decay: 0.95
  # Codebook hyperparameters (fully enabled for joint training)
  codebook_size: 512
  codebook_dim: null
  codebook_beta: 0.25
  codebook_decay: 0.90
  codebook_eps: 1e-5
  codebook_distance: l2
  codebook_cosine_normalize: false
  # Loss weights (VQ loss enabled from start)
  lambda_vq: 1.0
  lambda_ent: 1e-3
  lambda_psc: 1e-2
  lambda_card: 0.005
  psc_temp: 0.3

train:
  epochs: 120
  batch_size: 128
  lr: 1e-3
  num_workers: 8
  seed: 42
  models_dir: ./saved_models
  use_wandb: false
  wandb_project: joint-train
  # Cosine learning rate schedule with warmup
  use_cosine_schedule: true
  warmup_epochs: 10
  # Joint training specific settings
  codebook_init_epochs: 5  # Number of epochs to initialize codebook before full training
  codebook_init_max_batches: 50  # Max batches for codebook initialization

# Interpretability settings
interpretability:
  enabled: true
  max_batches: 20  # Limit for interpretability analysis
