hydra:
  run:
    dir: ./outputs/${train.wandb_project}/${data.dataset_name}/${data.split}/${now:%Y-%m-%d-%H-%M-%S}
  output_subdir: null

data: 
  dataset_name: enzymecommission
  split: structure
  split_similarity_threshold: 0.7
  data_dir: /home/wangx86/partoken/partoken-protein/data
  test_mode: false  # Set to true for testing with limited data sizes (100 train, 20 val, 20 test)

model:
  node_in_dim: [6, 3]
  node_h_dim: [100, 16]
  edge_in_dim: [32, 1]
  edge_h_dim: [32, 1]
  num_layers: 3
  drop_rate: 0.1
  pooling: sum
  seq_in: false
  # DiffPool specific parameters
  max_clusters: 30
  entropy_weight: 0.1
  link_pred_weight: 0.5

train:
  epochs: 120
  batch_size: 128
  lr: 1e-3
  num_workers: 8
  seed: 42
  models_dir: ./saved_models
  use_wandb: false
  wandb_project: diffpool
  # Cosine learning rate schedule with warmup
  use_cosine_schedule: false
  warmup_epochs: 5

# Interpretability settings
interpretability:
  enabled: true
  max_batches: 20  # Limit for interpretability analysis
